### PR TITLE
ci: enable cargo clippy, cargo fix, and cargo fmt in CI workflow (Part 2/2)

### LINKED ISSUE #501: MINOR: cargo clippy, fix and fmt
### What type of enhancement is this?

Other

### What does the enhancement do?

`cargo clippy`, `cargo fix`, and `cargo fmt` are widely used tools in the Rust community to catch common mistakes. However, the current CI workflow does not appear to include any actions that run these checks.

### Implementation challenges

Running `cargo clippy --fix`, `cargo fix` and `cargo +nightly fmt --all` would make changes to a large number of files (over 300 files), and there would still be some warnings that have to be addressed manually. This should probably be resolved in two separate PRs - one that simply performs automatic fixes by running the three commands and one that requires manual changes. And the corresponding CI workflow should be included in the second PR

### Related PRs

- [x] #502 
- [ ] A second PR that addresses the manual changes and integrate `cargo-clippy`, `cargo-fix` and `cargo-fmt` will be opened once the PR above is merged

### PR DESCRIPTION
**Pull request by minghuaw**
## What's changed and what's your intention?

This is the second of two planned pull requests aimed at integrating cargo clippy, cargo fix, and cargo fmt into the CI workflow.

Please explain IN DETAIL what the changes are in this PR and why they are needed:

The changes include:

1. Add two new jobs into the CI workflow
    a. rustfmt
    b. clippy
2. Fix `cargo-clippy` and `cargo-fix` warnings that require manual changes

## Checklist

- [x]  I have written the necessary rustdoc comments.
- [x]  I have added the necessary unit tests and integration tests.
- [x]  This PR does not require documentation updates.

## Refer to a related PR or issue link (optional)

Closes #501

### CODE REVIEW

File: src/placement-center/src/storage/engine.rs [hunk 1]
```diff
@@ -159,7 +159,7 @@ fn engine_prefix_list(
 
     let data_list = rocksdb_engine_handler.read_prefix(cf, &prefix_key_name);
     let mut results = Vec::new();
-    for raw in data_list {
+    if let Ok(raw) = data_list {
```
Comment (minghuaw) [inline src/placement-center/src/storage/engine.rs:162]: @socutes Is this error supposed to be propagated upwards?

File: src/placement-center/src/raftv1/rocksdb.rs [hunk 2]
```diff
@@ -355,7 +355,7 @@ impl RaftMachineStorage {
         }
     }
 
-    #[warn(dead_code)]
+    #[allow(dead_code)]
```
Comment (minghuaw) [inline src/placement-center/src/raftv1/rocksdb.rs:358]: Similarly, is this supposed to be #[allow(dead_code)] instead of #[warn(dead_code)]?

File: src/placement-center/src/raftv1/snapshot.rs [hunk 3]
```diff
@@ -52,7 +52,7 @@ impl RaftSnapshot {
         Ok(())
     }
 
-    #[warn(dead_code)]
+    #[allow(dead_code)]
```
Comment (minghuaw) [inline src/placement-center/src/raftv1/snapshot.rs:55]: Similarly, is this supposed to be #[allow(dead_code)] instead of #[warn(dead_code)]?

File: src/mqtt-broker/src/server/connection.rs [hunk 4]
```diff
@@ -23,8 +23,8 @@ static CONNECTION_ID_BUILD: AtomicU64 = AtomicU64::new(1);
 
 #[derive(Clone, PartialEq, PartialOrd)]
 pub enum NetworkConnectionType {
-    TCP,
-    TCPS,
+    Tcp,
+    Tcps,
```
Comment (minghuaw) [inline src/mqtt-broker/src/server/connection.rs:27]: Should this be `Tls` instead of `Tcps`? At least `Tls` is much more commonly used in the rust community

**Comment by socutes** [comment]
@minghuaw I just merged #507 and found a code conflict in this PR, please deal with it.

**Comment by minghuaw** [comment]
> @minghuaw I just merged #507 and found a code conflict in this PR, please deal with it.

@socutes Fixed :)

**Review by socutes — APPROVED** [review]
LGTM
